Add nowrap parameter
dale-roberts/MouseUnSnag pull request #4
Opened 2018-10-23 03:27 UTC by gillius

Fixes https://github.com/dale-roberts/MouseUnSnag/issues/3

2019-01-17 06:36 UTC, patricknelson commented
FYI @gillius the logic in this is backwards. By default, it disables wrapping and when you add `/nowrap` it enables wrapping, which had me confused. If it wraps by default, the option should be called `/nowrap` and the variable should be called `nowrap` and you need to negate `wrap` instead.

I posted some comments inline.

2019-01-17 06:47 UTC, patricknelson requested changes

2019-01-17 06:47 UTC, patricknelson commented on MouseUnSnag.cs
> +    private bool wrap = true;
You should call this `nowrap` and default this value to `false`...

```suggestion
    private bool nowrap = false;
```

2019-01-17 06:47 UTC, patricknelson commented on MouseUnSnag.cs
> +        else if (wrap && StuckDirection.X != 0)
... and then negate that here:

```suggestion
        else if (!nowrap && StuckDirection.X != 0)
```

2019-01-17 18:44 UTC, patricknelson commented
Got a PR to fix your PR here: https://github.com/gillius/MouseUnSnag/pull/

<img src="https://user-images.githubusercontent.com/4269377/51340690-71272580-1a44-11e9-9012-1a482625f1d5.jpg" width=250>

2025-06-24 17:44 UTC, gillius commented
closing and withdrawing this as it's on an inactive project.

2025-06-24 17:44 UTC, closed without merging

2025-06-24 22:36 UTC, patricknelson commented
Yes, and for reference, the repo is now hosted here in the `MouseUnsnag` org: https://github.com/MouseUnSnag/MouseUnSnag

So, the project is still active, it's just rarely updated now as far as I can tell. 😁

2025-06-25 13:19 UTC, gillius commented
No worries, I just wanted to remove this from my list of open PRs. I've not used the project in a long time since I updated my monitors to the same size and resolution and my work environment has switched to mac.